// <auto-generated />
using System;
using Infra.Catalogo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations.Catalogo
{
    [DbContext(typeof(CatalogoContext))]
    [Migration("20230628003407_Produtos-Dump")]
    partial class ProdutosDump
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Catalogo.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("531c2ebe-da2d-4d73-9467-d4022e1e62f4"),
                            Codigo = 1,
                            Nome = "Lanche"
                        },
                        new
                        {
                            Id = new Guid("699634a1-e07d-47c2-8a38-24fe93c9a3cf"),
                            Codigo = 2,
                            Nome = "Acompanhamento"
                        },
                        new
                        {
                            Id = new Guid("8b2c1301-b57f-4c2c-bf55-0a137a59b335"),
                            Codigo = 3,
                            Nome = "Sobremesa"
                        },
                        new
                        {
                            Id = new Guid("42963efa-df1b-4583-93fc-a41e15c8b69c"),
                            Codigo = 4,
                            Nome = "Bebida"
                        });
                });

            modelBuilder.Entity("Domain.Catalogo.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d98039d-cef1-42d7-970e-f2c256c427a9"),
                            Ativo = true,
                            CategoriaId = new Guid("45dd547f-5209-49c6-8cd1-ee5c384e93f2"),
                            DataCadastro = new DateTime(2023, 6, 28, 0, 34, 6, 839, DateTimeKind.Utc).AddTicks(2868),
                            Descricao = "Hambúrguer de carne com queijo, alface e tomate",
                            Imagem = "cheeseburger.jpg",
                            Nome = "Cheeseburger",
                            QuantidadeEstoque = 0,
                            Valor = 28m
                        },
                        new
                        {
                            Id = new Guid("b06c4c8a-c360-43a5-a786-95a2193b9181"),
                            Ativo = true,
                            CategoriaId = new Guid("9449c867-2f9e-4a3c-8e5f-06d18b788e88"),
                            DataCadastro = new DateTime(2023, 6, 28, 0, 34, 6, 839, DateTimeKind.Utc).AddTicks(2891),
                            Descricao = "Batatas cortadas em palitos e fritas até ficarem crocantes.",
                            Imagem = "batata_frita.jpg",
                            Nome = "Batata Frita",
                            QuantidadeEstoque = 0,
                            Valor = 8m
                        },
                        new
                        {
                            Id = new Guid("903562cf-1368-4e93-9de3-93f88b1407be"),
                            Ativo = true,
                            CategoriaId = new Guid("90c75224-78fa-4ef1-8b0c-c328781709a4"),
                            DataCadastro = new DateTime(2023, 6, 28, 0, 34, 6, 839, DateTimeKind.Utc).AddTicks(2897),
                            Descricao = "Bebida gaseificada e refrescante",
                            Imagem = "refrigerante.jpg",
                            Nome = "Coca-Cola - Lata",
                            QuantidadeEstoque = 0,
                            Valor = 5m
                        },
                        new
                        {
                            Id = new Guid("b5c14afa-c57b-4d9e-b145-400b428c0849"),
                            Ativo = true,
                            CategoriaId = new Guid("8293ecf7-3cab-4a63-99e9-d23d7ea5cd67"),
                            DataCadastro = new DateTime(2023, 6, 28, 0, 34, 6, 839, DateTimeKind.Utc).AddTicks(2902),
                            Descricao = "Sorvete cremoso de baunilha coberto com calda de chocolate e pedaços de chocolate crocantes.",
                            Imagem = "sundae_chocolate.jpg",
                            Nome = "Sundae de Chocolate",
                            QuantidadeEstoque = 0,
                            Valor = 12m
                        });
                });

            modelBuilder.Entity("Domain.Catalogo.Produto", b =>
                {
                    b.HasOne("Domain.Catalogo.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Domain.Catalogo.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
