// <auto-generated />
using System;
using Infra.Autenticacao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations.Autenticacao
{
    [DbContext(typeof(AutenticacaoContext))]
    [Migration("20230605150356_Initial_Acesso")]
    partial class Initial_Acesso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Autenticacao.AcessoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_usuario");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role_usuario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("acesso_usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72dbfdab-ab02-41c3-b4f8-3de33e0faf96"),
                            NomeUsuario = "fiapUser",
                            Role = 0,
                            Senha = "BF16FADFBDF1F8450D143857C08A8ACB70033CC48D18B22037E18A8CA7081F636A0B805E5241E5E30959A21EE773C3293251A34923A8E77925DD140116F25293"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
