apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    name: postgres-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: \\c\\techchallengedb\\soat1_grp13
