apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api-container
          image: christiandmelo/tech-challenge-soat1-grp13:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
